### ISSUE TITLE
NullReferenceException in CreateAndInitializePage

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/Sitecore.Support.119570#1]
NullReferenceException in CreatePage.CreateAndInitializePage
```
ERROR Cannot start analytics Tracker
Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Sitecore.Support.119570
   at Sitecore.Support.Analytics.Pipelines.InitializeTracker.CreatePage.CreateAndInitializePage(HttpContextBase httpContext, CurrentInteraction visit)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Analytics.DefaultTracker.StartTracking()
```

**Comment by AlenPelin** [comment]
Fixed in 8.1.3.1
